version: '1'
image_name: ollama
apis:
  - inference
  - safety
  - embeddings
providers:
  inference:
    - provider_id: ollama
      provider_type: remote::ollama
      config:
        url: http://localhost:11434
  safety:
    - provider_id: llama-guard
      provider_type: inline::llama-guard
      config: { }
metadata:
  tags: [ ]
models:
  - metadata: { }
    model_id: llama3.2:3b
    provider_id: ollama
  - metadata:
      model_type: embedding
    model_id: granite-embedding:latest
    provider_id: ollama